services:
  nginx:
    image: nginx:alpine
    hostname: fancystore.com
    networks:
      edge:
        aliases:
          - fancystore.com
      appnet: {}
    #ports:
    #  - "8080:80"       # expose nginx on port 8080
    volumes:
      - ./confs/nginx/:/etc/nginx/
      - ./out/nginx/:/var/log/nginx
    depends_on:
      - web

  web:
    image: bkimminich/juice-shop:latest
    networks: [appnet]
    expose:
      - "3000"        # only visible inside appnet

  attacker:
    image: kalilinux/kali-rolling:latest
    networks: [edge]
    environment:
      - TARGET_HOST=fancystore.com
      - TARGET_PORT=80
      - ATTACK_TYPE=sql_injection
      - ATTACK_PHASE=automated
    volumes:
      - ./confs/attacker/attack.sh:/attack.sh:ro
      - ./confs/attacker/attack_scripts/:/opt/scripts/:ro
      - ./out/attacker/:/opt/output/
      - ./out/logs/:/opt/logs/
    depends_on:
      - nginx
    command: ["bash", "-c", "apt-get update && apt-get install -y python3 python3-pip curl wget python3-requests python3-dnspython nmap dirb git sqlmap slowhttptest && bash /attack.sh --target http://fancystore.com"]

  user:
    image: alpine:latest
    networks: [edge]
    volumes:
      - ./confs/user/benign.sh:/benign.sh:ro
    depends_on:
      - nginx

networks:
  edge:
    driver: bridge
  appnet:
    driver: bridge
