version: "3.8"

services:
  victim1:
    build:
      context: ./victim1
      dockerfile: Dockerfile
    container_name: docker_victim1_1
    privileged: true
    network_mode: bridge
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
      - AUDIT_CONTROL
      - AUDIT_WRITE
    volumes:
      - ./victim1/raw:/data/raw
    environment:
      - SERVICE_NAME=victim1

  victim2:
    build:
      context: ./victim2
      dockerfile: Dockerfile
    container_name: docker_victim2_1
    privileged: true
    network_mode: bridge
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
      - AUDIT_CONTROL
      - AUDIT_WRITE
    volumes:
      - ./victim2/raw:/data/raw
    environment:
      - SERVICE_NAME=victim2