version: '3.8'
services:
  webapp:
    ports:
      - "8081:80"
    environment:
      - VARIANT_ID=lowscan_stealthy
      - EXPERIMENT_TIMESTAMP=20250714_121848
    volumes:
      - ../../data/logs/lowscan_stealthy:/var/log
      - ../../data/logs/lowscan_stealthy/pcap:/data/raw
      - ../../data/logs/lowscan_stealthy/output:/opt/output

  attacker:
    environment:
      - VARIANT_ID=lowscan_stealthy
      - EXPERIMENT_TIMESTAMP=20250714_121848
    volumes:
      - ../../data/logs/lowscan_stealthy/output:/opt/output
      - ../../data/logs/lowscan_stealthy/logs:/opt/logs

  tcpdump:
    environment:
      - VARIANT_ID=lowscan_stealthy
      - EXPERIMENT_TIMESTAMP=20250714_121848
    volumes:
      - ../../data/logs/lowscan_stealthy/pcap:/pcaps
      - ../../data/logs/lowscan_stealthy/logs:/logs

networks:
  attacknet:
    name: "lowscan_stealthy_net"
