services:
  web:
    image: bkimminich/juice-shop:latest
    networks: [appnet]
    expose:
      - "3000"        # only visible inside appnet

  nginx-waf:
    image: owasp/modsecurity-crs:nginx
    hostname: fancystore.com
    networks: 
      edge:
        aliases:
          - fancystore.com
      appnet: {}
    #ports:
    #  - "8080:8080"       # clients hit nginx with integrated WAF
    environment:
      BACKEND: http://web:3000
      PROXY: 1
      PORT: 8080
      MODSEC_AUDIT_LOG_FORMAT: JSON
      MODSEC_AUDIT_LOG: /var/log/modsecurity/audit.log
    volumes:
      - ./confs/waf/:/etc/modsecurity/
      - ./out/waf/nginx/:/var/log/nginx
      - ./out/waf/modsecurity/:/var/log/modsecurity
    depends_on:
      - web

  attacker:
    image: kalilinux/kali-rolling:latest
    networks: [edge]
    environment:
      - TARGET_HOST=fancystore.com
      - TARGET_PORT=8080
      - ATTACK_TYPE=sql_injection
      - ATTACK_PHASE=automated
      - WAF_MODE=enabled
    volumes:
      - ./confs/attacker/attack.sh:/attack.sh:ro
      - ./confs/attacker/attack_scripts/:/opt/scripts/:ro
      - ./out/waf/attacker/:/opt/output/
      - ./out/waf/logs/:/opt/logs/
      - ./out/waf/attacker/:/log
    depends_on:
      - nginx-waf
    command: ["bash", "-c", "apt-get update && apt-get install -y python3 python3-pip curl wget python3-requests python3-dnspython nmap dirb git sqlmap slowhttptest tcpdump && bash /attack.sh --target http://fancystore.com:8080"]

  user:
    image: python:3.9-alpine
    networks: [edge]
    environment:
      - TARGET_HOST=fancystore.com
      - TARGET_PORT=8080
      - WAF_MODE=enabled
    volumes:
      - ./confs/user/benign_enhanced.py:/benign_enhanced.py:ro
      - ./out/waf/user/:/opt/output/
    depends_on:
      - nginx-waf
    command: ["sh", "-c", "pip install requests && python /benign_enhanced.py http://fancystore.com:8080"]

networks:
  edge:
    driver: bridge
    name: ras-waf-edge
  appnet:
    driver: bridge
    name: ras-waf-appnet
